apiVersion: v1
kind: Service
metadata:
  name: service-vector-aggregator
  namespace: {{ .Values.NAMESPACE }}
spec:
  selector:
    app: vector-aggregator
  ports:
    - name: vector
      protocol: TCP
      port: {{ .Values.VECTOR_AGGREGATOR.PORT }}
      targetPort: {{ .Values.VECTOR_AGGREGATOR.PORT }}
  type: ClusterIP